title: Awesome ClickHouse
query: clickhouse stars:>50 archived:false
root:
  categories:
    - title: Language bindings
      categories:
        - title: C/C++
          prompt: C and C++ binding, library, or SDK (not to be confused with C# and .NET)
        - title: Elixir
          prompt: Elixir binding, library or sdk
        - title: JavaScript/Typescript
          prompt: JavaScript and Typescript binding, library or sdk
        - title: Golang
          prompt: Golang binding, library or sdk
        - title: Java
          prompt: Java and JDBC binding, library or sdk
        - title: .Net
          prompt: .Net and C# binding, library or sdk
        - title: ODBC
          prompt: ODBC binding, library or sdk
        - title: PHP
          prompt: PHP binding, library or sdk
        - title: Python
          prompt: Python binding, library or sdk
        - title: R
          prompt: R language binding, library or sdk
        - title: Ruby
          prompt: Ruby binding, library or sdk
        - title: Rust
          prompt: Rust binding, library or sdk
        - title: Scala
          prompt: Scala binding, library or sdk
        - title: Other sdk/libraries
          prompt: Other binding, library or sdk
    - title: UIs
      categories:
        - title: GUI
          prompt: Graphical user interface
        - title: CLI
          prompt: Command line interfaces and tools
        - title: CHUI(Chat-based User Interface) or CHUBACA(Chat-Based Client:)
          prompt: Chat interfaces supporting ClickHouse queries through natural language
    - title: Integrations
      categories:
        - title: Data Transfer and Synchronization
          prompt: Tools and utilities for data movement and synchronization
        - title: Metrics and Monitoring
          prompt: Projects concerned with metrics collection and monitoring
        - title: Deployment and Management Tools
          prompt: Applications for deploying and managing ClickHouse instances
        - title: Data Visualization and Analysis
          prompt: Solutions for visualizing and analyzing data using ClickHouse
        - title: ETL and Data Processing
          prompt: ETL tools and data processing applications
    - title: Ops
      prompt: Solutions for database administrators to manage and maintain ClickHouse infrastructures in day-to-day operations
    - title: Documentation
      prompt: Documentation and guides
    - title: Examples
      prompt: Sample projects and demonstrations for ClickHouse usage and integration
